### ISSUE TITLE
Please add aurelia-http-client

### ISSUE THREAD

**Issue by MiniverCheevy** [aurelia/script#1]
**I'm submitting a feature request**

I understand that this is a work in progress, but I feel like the http client is something that most developers will want.

**Comment by EisenbergEffect** [comment]
We'll have script-tag compatible builds of all libraries eventually.

**Comment by jods4** [comment]
I am not sure about this.

There are _lots_ of different optional modules that appeal to different people: i18n, dialogs, animations, validation, async, http-client, fetch-client, and more. For each one you could say "it is something that most/many developers will want". Yet probably nobody wants them all.

For instance, I build my networking layer directly on top of the Fetch API and use none of http-client nor fetch-client. I personally don't see much value in those packages.

I feel like the core should be what _everybody_ uses, in a nice package easy to get started / fiddle around. Then people can add on top of it whatever optional deps they want/need.

Random idea: maybe publish `aurelia-all` beside this, which is the mega-fat-has-it-all bundle for fiddles? But I don't think the goal is to produce 100s of different bundles...

**Comment by MiniverCheevy** [comment]
I can see the benefit of an aurelia-all and leaving this one as it.
