### ISSUE TITLE
Add an unpkg field to package.json

### ISSUE THREAD

**Issue by jsobell** [aurelia/script#14]
A bare URL returns the `browser` linked file, but we should really support the official `unpkg` entry.

Should we also be referencing the .min version?

Obviously we can do this by specifying the full path:
`https://unpkg.com/aurelia-script@1.2.0/dist/aurelia_router.umd.min.js`
but if we're creating blogs and samples referring to the short-version
`https://unpkg.com/aurelia-script@1.2.0`
then we might want to use the 66KB bundle instead.

**Comment by EisenbergEffect** [comment]
@bigopon Do you know how to get this configured as @jsobell recommends. I think he's spot on but I haven't had a chance to look into what's required to configure it.

**Comment by bigopon** [comment]
@EisenbergEffect @jsobell From the look of `unpkg` doc, it's a simple `unpkg` field in `package.json`. I'll create a PR soon.

**Comment by EisenbergEffect** [comment]
Sounds good. Let's definitely point it to the UMD minified version. I can do a release as soon as that's ready.
