### ISSUE TITLE
Example site not working in Firefox/Edge & IE

### ISSUE THREAD

**Issue by Dreamwalker666** [aurelia/script#17]
**I'm submitting a bug report**

* **Library Version:**
1.3.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
11.1.0

* **NPM Version:**
6.4.1

* **Browser:**
Firefox 64.0b10 (64-bit)
Microsoft Edge 42.17134.1.0
Chrome Version 70.0.3538.102
IE 11.345.171134.0

**Current behavior:**
Example site only renders in chrome others get the following errors

Firefox reports: 
SyntaxError: the import keyword may only appear in a module - aurelia_router.umd.js:985:17
ReferenceError: au is not defined - localhost:5:11
	<anonymous> http://localhost/:5:11
	InnerModuleEvaluation self-hosted:4288:5
	evaluation self-hosted:4241:9

IE reports:
SCRIPT1014: Invalid character - aurelia_router.umd.js (15,18)

Edge reports: 
SCRIPT1002: SCRIPT1002: Syntax error - aurelia_router.umd.js (985,18)
SCRIPT5009: SCRIPT5009: 'au' is not defined localhost (5,5)

(IIS Pointed at example folder on localhost)

* **What is the expected behavior?**
Renders in all latest versions of browsers

* **What is the motivation / use case for changing the behavior?**
Creating a simple static site to test

**Comment by bigopon** [comment]
@Dreamwalker666 Hi, it is supposed to work with browser that supports `import()` API.

That said, I think we can also distribute a version without `EsmLoader` so folks can just use static templating feature without issues, but it's severely limited because there is no module loading. SystemJSLoader (aka loader-default could be employed but I'm nt sure). Thoughts @EisenbergEffect ?

@Dreamwalker666 Can you describe a bit more about your use case? Do you test with modules or just some simple class, all in one file?

**Comment by Dreamwalker666** [comment]
1. I am guessing dynamic import must be supported?  as basic support is in for Edge and Firefox.

2.  I'm actually just writing a quick frontend site and quick visual results are key not a nicely packaged site.  I am also learning Aurelia so this is a quick entry point without getting into details of build processes.

**Comment by EisenbergEffect** [comment]
@bigopon I'm not sure that we should introduce SystemJS into this.

**Comment by lancelot316** [comment]
I think part of the problem with Firefox is that you need to in include a type="module" on the script tag. 
`<script src='https://cdn.jsdelivr.net/npm/aurelia-script@1.3.0' type='module'></script>` that clears the syntax error but the au is not defined Reference Error still exists.

**Comment by bigopon** [comment]
@lancelot316 It's not because we don't specify it as script type module, reference in MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import

> There is also a function-like dynamic import(), which does not require scripts of type="module".

**Comment by bigopon** [comment]
@lancelot316 It's not because we don't specify it as script type module, reference in MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import

> There is also a function-like dynamic import(), which does not require scripts of type="module".

It's because those browsers haven't added support for it yet. In a fully supported environment, it should be able to loaded those scripts just fine.

**Comment by lancelot316** [comment]
@bigopon so basically the issue is the dynamic import feature is not implemented yet in Edge, or Firefox ,correct?
[dynamic import compatibility](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#Browser_compatibility)

**Comment by bigopon** [comment]
Yes. It's been that all along

**Comment by Dreamwalker666** [comment]
I'll let you judge but I think this issue just warrants an update to the repo docs saying this is only supported in browsers with dynamic import.  Then link to the "can I use page" for it.  
https://caniuse.com/#feat=es6-module-dynamic-import

**Comment by EisenbergEffect** [comment]
@bigopon Can you make some improvements in the readme?

**Comment by phissionmailed** [comment]
@Dreamwalker666 I had the same issue a couple of months ago. As already stated, the problem is that Edge and FireFox don't currently support dynamic module loading.

In this Aurelia discourse thread I provided the workaround I did to add the support. It's basically a in-place SystemJS loader; without referencing SystemJS at all, so no dependency necessary.
https://discourse.aurelia.io/t/using-a-different-loader-in-aurelia-script/1867

So far it's working perfectly in Chrome, Edge, and FireFox. I'm planning on going live even with this change in a month or two.

The workaround I consider a hack that I'll promptly remove once either Edge and FireFox support property dynamic module loading or the Aurelia team provides an official fix/patch.

I just love how I can quickly work with Aurelia without messy nodejs in the way to care about how ugly the hack may be. :)

**Comment by Dreamwalker666** [comment]
> @Dreamwalker666 I had the same issue a couple of months ago. As already stated, the problem is that Edge and FireFox don't currently support dynamic module loading.
> 
> In this Aurelia discourse thread I provided the workaround I did to add the support. It's basically a in-place SystemJS loader; without referencing SystemJS at all, so no dependency necessary.
> https://discourse.aurelia.io/t/using-a-different-loader-in-aurelia-script/1867
> 
> So far it's working perfectly in Chrome, Edge, and FireFox. I'm planning on going live even with this change in a month or two.
> 
> The workaround I consider a hack that I'll promptly remove once either Edge and FireFox support property dynamic module loading or the Aurelia team provides an official fix/patch.
> 
> I just love how I can quickly work with Aurelia without messy nodejs in the way to care about how ugly the hack may be. :)

I'll have a look at this I moved onto some other things :D but going back to some UI work soon.

Heres a link to the code changes for people finding this before the discourse https://discourse.aurelia.io/t/using-a-different-loader-in-aurelia-script/1867/6

**Comment by bigopon** [comment]
Just for awareness of aurelia script users, with the latest version of official plugins, it's now very easy to use plugins together with aurelia script. Simply do:

```js
aurelia.use
  .plugin(au.dialog.configure)
  .plugin(au.validation.configure)
  .plugin(au.store.configure, { initialState })
  .plugin(au.uiVirtualization.configure)
```

Of course, you will have to specify the right script tags pointing to correct version of those plugins. Typically can be found at `https://unpkg.com/aurelia-xxx@yyy` where `xxx` is the name of plugin and `yyy` is the version.

Codesandbox for testing purposes
  * With Aurelia Store: https://codesandbox.io/s/n3r48qvzjl
  * With Aurelia UI Virtualization: https://codesandbox.io/s/m781l8oyqj
  * With Aurelia Dialog: https://codesandbox.io/s/62lmyy16xn
  * With Aurelia Validation: https://codesandbox.io/s/6y1zzon47r

**Comment by euglv** [comment]
> 
> 
> > @Dreamwalker666 I had the same issue a couple of months ago. As already stated, the problem is that Edge and FireFox don't currently support dynamic module loading.
> > In this Aurelia discourse thread I provided the workaround I did to add the support. It's basically a in-place SystemJS loader; without referencing SystemJS at all, so no dependency necessary.
> > https://discourse.aurelia.io/t/using-a-different-loader-in-aurelia-script/1867
> > So far it's working perfectly in Chrome, Edge, and FireFox. I'm planning on going live even with this change in a month or two.
> > The workaround I consider a hack that I'll promptly remove once either Edge and FireFox support property dynamic module loading or the Aurelia team provides an official fix/patch.
> > I just love how I can quickly work with Aurelia without messy nodejs in the way to care about how ugly the hack may be. :)
> 
> I'll have a look at this I moved onto some other things :D but going back to some UI work soon.
> 
> Heres a link to the code changes for people finding this before the discourse https://discourse.aurelia.io/t/using-a-different-loader-in-aurelia-script/1867/6

This method does not work with custom components.
I am trying to import the following .js script:

```
const {bindable, bindingMode} = au;

export class RenderViewCustomElement {
    @bindable({ defaultBindingMode: bindingMode.twoWay }) test;
    constructor (){
        this.test = "Hello World!";
    }
}
```

But Chrome and Firefox throw `SyntaxError: Invalid or unexpected token` in place where  `@bindable` starts.
