### ISSUE TITLE
Example doesn't load if served from subdirectory. Problem with relative paths

### ISSUE THREAD

**Issue by MikeKovarik** [aurelia/script#19]
**I'm submitting a bug report**

* **Library Version:**
Aurelia Script 1.3.0

* **Browser:**
Chrome 71

* **Language:**
ESNext

**Current behavior:**
I cloned the repo, renamed it as `aurelia-script` placed it in my projects directory which is served as localhost. In browser i navigated to `http://localhost/aurelia-script/example/index.html` and the example app didn't load because of absolute paths. Aurelia doesn't load `app.js` relative to `http://localhost/aurelia-script/example/` but as an absolute path `http://localhost/app.js`.

I tried both umd and esm versions, results are the same.

I also tried changing `aurelia.setRoot('app.js', document.body)` to `aurelia.setRoot('./app.js', document.body)` in `index.html` but that doesn't work either.

Console log
```
INFO [aurelia] Aurelia Starting aurelia_router.esm.js:18060
INFO [aurelia] Aurelia Started aurelia_router.esm.js:979
GET http://localhost/app.js net::ERR_ABORTED 404 (Not Found)
_import @ aurelia_router.esm.js:979
loadModule @ aurelia_router.esm.js:1037
importViewModelResource @ aurelia_router.esm.js:10289
ensureViewModel @ aurelia_router.esm.js:11550
createController @ aurelia_router.esm.js:11528
_createControllerAndSwap @ aurelia_router.esm.js:11506
compose @ aurelia_router.esm.js:11598
compose @ aurelia_router.esm.js:11844
setRoot @ aurelia_router.esm.js:11958
aurelia.start.then @ (index):11
Promise.then (async)
(anonymous) @ (index):11
(index):1
Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: http://localhost/app.js
```

* **What is the expected behavior?**

The app should load and work correctly even if it's in a subdirectory.

I know the readme wants me to server `/example` but in production i cannot put the app at the top of my domain.

**Comment by bigopon** [comment]
It's supposed to behave like a normal `import('some/url')`. Though the loader is capable of adjusting base url for your case. Can you try the following in your startup:
```js
aurelia.get(au.Loader).baseUrl = `${location.href}`
```

**Comment by MikeKovarik** [comment]
Thanks! that worked for me. Though i couldn't find any `.get()` method on neither the UMD `au` nor in the `new Aurelia` instance.

So instead of:
```js
aurelia.get(au.Loader).baseUrl = `${location.href}`
```
I did this:
```js
import {Aurelia} from './aurelia_router.esm.js'
const aurelia = new Aurelia()
aurelia.loader.baseUrl = location.href // added this
aurelia.use.standardConfiguration().developmentLogging()
```

Anyway. It's odd that this doesn't happen under the hood and has to be done explicitly.

**Comment by bigopon** [comment]
@MikeKovarik My bad, I meant
```js
aurelia.container.get(...)
```

**Comment by bigopon** [comment]
@MikeKovarik @EisenbergEffect I think this can be closed

**Comment by eMBee** [comment]
to make this work with version 1.5.2 and `/#/routing` using the hash i had to do the following:

```
    <script src='scripts/aurelia_router.umd.min.js'></script>
    <script>
        aurelia = new au.Aurelia()
        aurelia.container.get(au.Loader).baseUrl = location.origin+location.pathname
        aurelia.use.standardConfiguration().developmentLogging()
        aurelia
          .start()
          .then(() => aurelia.setRoot('./src/app.js', document.body))
          .catch(ex => document.body.textContent = `Bootstrap error: ${ex}`)
    </script>
```

i suppose location.href works if there is no hash in the url.
