### ISSUE TITLE
Firefox mutation warning

### ISSUE THREAD

**Issue by Y-Less** [aurelia/script#2]
**I'm submitting a bug report**
- **Library Version:**
  1.0.2 (guess - I got it from this repo a few days again).

**Please tell us about your environment:**
- **Operating System:**
  Windows 7
- **Node Version:**
  N/A
- **NPM Version:**
  N/A
- **JSPM OR Webpack AND Version**
  N/A
  
  
- **Browser:**
  Firefox 46.0.1
- **Language:**
  ESNext

**Current behavior:**
I get the following warning in Firefox's console:

```
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create
aurelia-core.min.js:4:21492
```

**Expected/desired behavior:**

- **What is the expected behavior?**
  No prototype modifications.
- **What is the motivation / use case for changing the behavior?**
  Speed.

**Comment by EisenbergEffect** [comment]
It's just a warning, and it's related to polyfills.
