### ISSUE TITLE
[Discussion] Create a distribution for Es5 env

### ISSUE THREAD

**Issue by bigopon** [aurelia/script#25]
At the moment, aurelia script is intended to be use with `import()` API, making it only suitable for modern environment.

This leaves out environment like IE11 and below, old mobile browsers.

Maybe consider release a version of Aurelia script without any Loader implementation, so folks who wants to leverage Aurelia in Mvc environment for only enhacement, or app without any router can just use Aurelia templating/binding with static resources registration.

Only templating-binding + templating-resources + logging console need to be loaded properly, and are already taken cared with https://github.com/aurelia/script/blob/5e2cf294efee2d82bddae456d9f02fed8397cd29/build/index.full.js#L16-L28 so I think we just need to remove this line https://github.com/aurelia/script/blob/5e2cf294efee2d82bddae456d9f02fed8397cd29/build/index.full.js#L3 to do the above.

@EisenbergEffect

**Comment by EisenbergEffect** [comment]
I'd definitely like to support this scenario. Can you move ahead with this, just making sure that the previous scenarios all continue to work?

**Comment by bigopon** [comment]
@EisenbergEffect we will simply create another entry point file for es5 distribution, and remove the import loader line like mentioned above. One thing I'm not sure is how to name it. At the moment, we have these:

`aurelia.umd.js`: es6 + esm loader + umd
`aurelia.esm.js`: es6 + esm loader + es
`aurelia_router.umd.js`: es6 + esm loader + router + umd 
`aurelia_router.esm.js`: es6 + esm loader + router + es

**Comment by EisenbergEffect** [comment]
It's basically the same stuff without the loader, so maybe a postfix like `-no-loader`?

**Comment by bigopon** [comment]
`aurelia_no_loader.umd.js`?

I think it's ok. Then folks can plugin in a SystemJS/RequireJS loader and configure all the alias to make it flexible and usable in any environment, with Es5 distributed code. We can even put it in the read me how to configure the alias.

**Comment by EisenbergEffect** [comment]
Works for me :)
