### ISSUE TITLE
show.bind with binding behavior works - but show.bind expression evaluation fails

### ISSUE THREAD

**Issue by deap82** [aurelia/script#7]
**I'm submitting a bug report**

* **Library Version:**
Current

**Current behavior:**
I'm trying to use the InterceptBindingBehavior from this blog post; https://www.danyow.net/aurelia-binding-behaviors/ on a show.bind binding.
The interception works, but makes the evalution of whether the element should be shown or not fail.

See gist run: https://gist.run/?id=63cf42d8d753cdf62ff2c8c466a4f61e

**Expected/desired behavior:**
Make it possible to use binding behaviors on show.bind bindings.

* **What is the expected behavior?**
To be able to use binding behaviors on show.bind bindings.

* **What is the motivation / use case for changing the behavior?**
My need is to run code after the show.bind binding actually has changed the visibility of its' element. If there is some other way of doing that, please point me in the right direction. However, I thought this finding should be reported as this behavior is very unexpected, given that the behavior actually works, but the functionality of show.bind stops working.

**Comment by EisenbergEffect** [comment]
@jdanyow Can you look into this?

**Comment by jdanyow** [comment]
The custom "intercept" binding behavior from the blog post replaces the binding logic with a call to the method supplied to the binding behavior.

The example from the blog post logs the binding change and call the original binding method- your code is missing that part of the example. Here's the relevant part of the demo:

```js
    this.myFunc = (method, update, value) => {
      // log the intercepted binding method.
      let info = {
        color: '#'+Math.floor(Math.random()*16777215).toString(16), 
        method: method,
        value: value
      };
      this.intercepted.splice(0, 0, info);
      
      // call the intercepted binding method.
      update(value);             // <----------------- this is missing in your version
    };
```

**Comment by deap82** [comment]
@jdanyow  Aha, ok I missed that detail.
Does this mean the interceptor is run before the binding is updated?

I got my case working now, but my intention was to run some code after the binding has been updated, ie after the element actually has been hidden/shown in the DOM.

**Comment by deap82** [comment]
@jdanyow Aha, ok, I missed that detail.
Got my case working now.
So if I want to run my custom code after the element has been shown/hidden I can just place it after the "update(value);" statement?
